from .user import USER_MESSAGE_HANDLERS, USER_CALLBACK_HANDLERS
from .player import PLAYER_MESSAGE_HANDLERS, PLAYER_CALLBACK_HANDLERS
from .test import TEST_MESSAGE_HANDLERS, TEST_CALLBACK_HANDLERS


MESSAGE_HANDLERS = USER_MESSAGE_HANDLERS + PLAYER_MESSAGE_HANDLERS + TEST_MESSAGE_HANDLERS
CALLBACK_HANDLERS = USER_CALLBACK_HANDLERS + PLAYER_CALLBACK_HANDLERS + TEST_CALLBACK_HANDLERS